spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/livealone?serverTimezone=Asia/Seoul
    username: jangstudy
    password: wk135790
server:
  port: 8081
logging:
  level:
    org.springframework.r2dbc.core: debug