server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livealone?serverTimezone=Asia/Seoul
    username: jangstudy
    password: wk135790
  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: 9q28hinltgiahsd098ehan5optiugsdu908hnbrio5tu3h0w98BHNOP354H4R26f8wbnaet0a98ehgdspoih59083hwneodfghjso

